source $HOME/.functions.sh
source $HOME/.exports.sh
source $HOME/.aliases.sh
source $HOME/.iterm2_shell_integration.sh

# Z
. /usr/local/etc/profile.d/z.sh

# virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

# direnv
eval "$(direnv hook bash)"

# show virtual env activated using direnv
show_virtual_env() {
  if [ -n "$VIRTUAL_ENV" ] && [ -n "$DIRENV_DIR" ]; then
    echo "($(basename $VIRTUAL_ENV)) "
  fi
}

PS1='$(show_virtual_env)'$PS1
