source $HOME/.antigen.sh
source $HOME/.p10k.zsh
source $HOME/.functions.sh
source $HOME/.exports.sh
source $HOME/.aliases.sh
source $HOME/.secret/*.sh
[[ ! -f $HOME/ssh-agent.sh ]] || source $HOME/ssh-agent.sh
