#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_brew_packages {
  if ! type "brew" &> /dev/null; then
    eerr "Brew must be installed first..."; exit 1
  fi

  einf "Updating brew"
  brew update

  einf "Tapping brews"
  grep -v '^#' $BREW_TAPS | xargs -L 1 brew tap

  einf "Installing brew packages"
  grep -v '^#' $BREW_PACKAGES | xargs brew install
}

askdo_os Mac install_brew_packages "Install brew packages?"
