#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_apt_packages {
  if ! type "apt-get" &> /dev/null; then
    eerr "apt-get must be installed first..."; exit 1
  fi

  if [ "$(lsb_release -cs)" = "bionic" ]; then
    einf "Adding apt keys"
    grep -v '^#' $APT_KEY_LISTS | xargs -L 1 curl -fsSL | sudo apt-key add -
    einf "Adding apt lists"
    grep -v '^#' $APT_LISTS | xargs -I {} sudo add-apt-repository {}
  else
    einf "System in not bionic - not adding apt lists"
  fi

  einf "Updating apt-get"
  sudo apt-get update

  einf "Installing apt packages"
  sudo -v
  grep -v '^#' $APT_PACKAGES | xargs sudo apt-get install --no-install-recommends -y
}

askdo_os Linux install_apt_packages "Install apt packages?"
