#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_managers {
  if ! type "n" > /dev/null; then
    einf "Installing n"
    curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y
  else
    printf "n already installed... skipping\n"
  fi
}

askdo install_managers "Install managers (n)?"
