#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_managers {
  if ! type "antigen" &> /dev/null; then
    einf "Installing antigen"
    git clone https://github.com/zsh-users/antigen $VENDOR/zsh-antigen
  else
    printf "antigen already installed... skipping\n"
  fi
}

askdo install_managers "Install managers (n)?"
