#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_python {
  if type "pip" > /dev/null; then
    einf "Python already installed... skipping"
    return
  fi

  einf "Installing python"
  brew install python
  brew install python3

  einf "Upgrading pip"
  pip install --upgrade pip
  pip install --upgrade setuptools
  pip3 install --upgrade pip
  pip3 install --upgrade setuptools
}

askdo install_python "Install python?"
