#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_casks {
  if ! type "brew" &> /dev/null; then
    eerr "Brew must be installed first..."; exit 1
  fi

  einf "Updating brew"
  brew update

  einf "Installing brew cask packages"
  grep -v '^#' $CASK_PACKAGES | \
  while read CASK; do
    printf "Installing $CASK... "

    if brew list --versions $CASK > /dev/null 2>&1; then
      printf "already installed\n"
    else
      printf "\n"
      brew install $CASK
    fi
  done

}

askdo_os Mac install_casks "Install brew cask packages?"
