#!/bin/sh

# import helpers
source `dirname $0`/helpers

function setup_editor {
  if is_mac; then
    VSCODE_PATH="${HOME}/Library/Application\ Support/Code/User"
  elif [ -d "${HOME}/.vscode-server" ]; then
    VSCODE_PATH="${HOME}/.vscode-server/data/Machine"
  else
    VSCODE_PATH="${HOME}/.config/Code/User"
  fi

  einf "Linking editor configs"
  mkdir -p $VSCODE_PATH
  # VSCode Configuration File, attempt to remove existing settings and link ours
  mv $VSCODE_PATH/settings.json $VSCODE_PATH/settings.json.bak >/dev/null
  link $DOTFILES_EDITORS/vscode.json $VSCODE_PATH/settings.json
}

# Setup generic OS
function setup_env {
  einf "Linking shell configs"
  link $DOTFILES_SHELL/antigen $HOME/.antigen.sh
  link $DOTFILES_SHELL/functions $HOME/.functions.sh
  link $DOTFILES_SHELL/exports $HOME/.exports.sh
  link $DOTFILES_SHELL/aliases $HOME/.aliases.sh
  mkdir -p $HOME/.secret
  touch $HOME/empty.sh
  link $DOTFILES_SHELL/p10k_conf $HOME/.p10k.zsh
  link $DOTFILES_SHELL/profile $HOME/.profile
  link $DOTFILES_SHELL/zshrc $HOME/.zshrc

  setup_editor

  einf "Linking Git config"
  link $DOTFILES_SHELL/gitconfig $HOME/.gitconfig

  #einf "Linking pip config"
  #mkdir -p $HOME/.pip
  #link $DOTFILES_SHELL/pip.conf $HOME/.pip/pip.conf

  einf "Linking pythonrc"
  link $DOTFILES_SHELL/pythonrc $HOME/.pythonrc

  einf "Linking ssh_config"
  mkdir -p $HOME/.ssh/sock
  link $DOTFILES_SHELL/ssh_config $HOME/.ssh/config

  einf "Setting up gnupg"
  mkdir -p $HOME/.gnupg
  link $DOTFILES_SHELL/gpg_conf $HOME/.gnupg/gpg.conf
  link $DOTFILES_SHELL/gpg_agent_conf $HOME/.gnupg/gpg-agent.conf

  einf "Setting up Projects directory"
  mkdir -p $HOME/Projects

  einf "Setting up gopath"
  mkdir -p $HOME/go/src/github.com
  if [ ! -L $HOME/go/src/github.com/LukeHandle ]; then
    mkdir -p $HOME/Projects/Go
    link $HOME/Projects/Go $HOME/go/src/github.com/LukeHandle
  fi

  if is_linux; then
    einf "Setting up ssh-agent_wsl"
    link $DOTFILES_SHELL/ssh-agent_wsl $HOME/ssh-agent.sh
  fi

  einf "Changing shell to zsh"
  if is_mac; then
    sudo -v
    echo "$(which zsh)" | sudo tee -a /etc/shells
  fi
  chsh -s $(which zsh)

  if is_mac; then
    einf "Open iTerm 2, set the custom configuration folder to ~/.dotfiles/shell"
    einf "Open BetterTouchTool, import Preset ~/.dotfiles/shell/Default.bttpreset"
  fi
}

askdo setup_env "Setup environment?"
