#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function setup_env {
  einf "Linking shell configs"
  link $DOTFILES_SHELL/functions $HOME/.functions.sh
  link $DOTFILES_SHELL/exports $HOME/.exports.sh
  link $DOTFILES_SHELL/aliases $HOME/.aliases.sh
  link $DOTFILES_SHELL/bash_profile $HOME/.bash_profile

  einf "Linking editor configs"
  # VSCode Configuration File, attempt to remove existing settings and link ours
  mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.json.bak
  link $DOTFILES_EDITORS/vscode.json $HOME/Library/Application\ Support/Code/User/settings.json

  einf "Linking github configs"
  link $DOTFILES_SHELL/gitconfig $HOME/.gitconfig

  einf "Linking karabiner config"
  mkdir -p $HOME/.config/karabiner
  link $DOTFILES_SHELL/karabiner.json $HOME/.config/karabiner/karabiner.json

  einf "Linking ssh_config"
  mkdir -p $HOME/.ssh
  link $DOTFILES_SHELL/ssh_config $HOME/.ssh/config

  einf "Linking spectacle config"
  link $DOTFILES_SHELL/spectacle.json $HOME/Library/Application\ Support/Spectacle/Shortcuts.json

  einf "Linking iTerm 2 config"
  link $DOTFILES_SHELL/iterm_settings $HOME/Library/Preferences/com.googlecode.iterm2.plist
}

askdo setup_env "Setup environment?"
