#!/bin/bash

# source helpers file
source `dirname $0`/helpers

# Install brew
function uninstall_env {
  einf "Unlinking shell configs"
  rm -f $HOME/.functions.sh
  rm -f $HOME/.exports.sh
  rm -f $HOME/.aliases.sh
  rm -f $HOME/.bash_profile

  einf "Unlinking editor configs"
  rm -f $HOME/Library/Application\ Support/Code/User/settings.json

  einf "Unlinking github configs"
  rm -f $HOME/.gitconfig

  einf "Unlinking karabiner"
  rm -f $HOME/.config/karabiner/karabiner.json

  einf "Unlinking ssh_config"
  rm -f $HOME/.ssh/config

  einf "Unlinking spectacle config"
  rm -f $HOME/Library/Application\ Support/Spectacle/Shortcuts.json
}

askdo uninstall_env "Unlink environment files?"
